version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing backend dependencies...
      - cd backend && npm install
      - cd ..
      - echo Installing frontend dependencies...
      - cd frontend && npm install
  build:
    commands:
      - echo Building React frontend...
      - npm run build
      - echo Copying build to backend/public...
      - rm -rf ../backend/public
      - mkdir -p ../backend/public
      - cp -r build/* ../backend/public/
  post_build:
    commands:
      - echo Preparing final artifacts...
artifacts:
  files:
    - '**/*'  # Include everything from root
